In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data.csv')

In [3]:
df.head()

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
1,Bachelors,2013,Pune,1,28,Female,No,3,1
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
3,Masters,2016,Bangalore,3,27,Male,No,5,1
4,Masters,2017,Pune,3,24,Male,Yes,2,1

In [4]:
df.tail()

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
4648,Bachelors,2013,Bangalore,3,26,Female,No,4,0
4649,Masters,2013,Pune,2,37,Male,No,2,1
4650,Masters,2018,New Delhi,3,27,Male,No,5,1
4651,Bachelors,2012,Bangalore,3,30,Male,Yes,2,0
4652,Bachelors,2015,Bangalore,3,33,Male,Yes,4,0

In [5]:
df.shape

(4653, 9)

In [6]:
df.columns

Index(['Education', 'JoiningYear', 'City', 'PaymentTier', 'Age', 'Gender',
       'EverBenched', 'ExperienceInCurrentDomain', 'LeaveOrNot'],
      dtype='str')

In [7]:
df.dtypes

Education                      str
JoiningYear                  int64
City                           str
PaymentTier                  int64
Age                          int64
Gender                         str
EverBenched                    str
ExperienceInCurrentDomain    int64
LeaveOrNot                   int64
dtype: object

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4653 entries, 0 to 4652
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Education                  4653 non-null   str
 1   JoiningYear                4653 non-null   int64
 2   City                       4653 non-null   str
 3   PaymentTier                4653 non-null   int64
 4   Age                        4653 non-null   int64
 5   Gender                     4653 non-null   str
 6   EverBenched                4653 non-null   str
 7   ExperienceInCurrentDomain  4653 non-null   int64
 8   LeaveOrNot                 4653 non-null   int64
dtypes: int64(5), str(4)
memory usage: 327.3 KB

In [9]:
df.isnull().sum()

Education                    0
JoiningYear                  0
City                         0
PaymentTier                  0
Age                          0
Gender                       0
EverBenched                  0
ExperienceInCurrentDomain    0
LeaveOrNot                   0
dtype: int64

In [11]:
print(df.columns)

Index(['Education', 'JoiningYear', 'City', 'PaymentTier', 'Age', 'Gender',
       'EverBenched', 'ExperienceInCurrentDomain', 'LeaveOrNot'],
      dtype='str')

In [12]:
df.drop_duplicates(inplace=True)

In [13]:
df[df['Age'] > 30]

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
6,Bachelors,2015,New Delhi,3,38,Male,No,0,0
7,Bachelors,2016,Bangalore,3,34,Female,No,2,1
9,Masters,2017,New Delhi,2,37,Male,No,2,0
...,...,...,...,...,...,...,...,...,...
4641,Bachelors,2016,Bangalore,1,33,Female,No,0,1
4643,Bachelors,2013,Bangalore,3,31,Female,No,5,0
4644,Bachelors,2015,Pune,3,32,Female,Yes,1,1
4645,Masters,2017,Pune,2,31,Female,No,2,0
4649,Masters,2013,Pune,2,37,Male,No,2,1

In [14]:
df[['Education', 'Age', 'City']]

      Education  Age       City
0     Bachelors   34  Bangalore
1     Bachelors   28       Pune
2     Bachelors   38  New Delhi
3       Masters   27  Bangalore
4       Masters   24       Pune
...         ...  ...        ...
4645    Masters   31       Pune
4647  Bachelors   30       Pune
4649    Masters   37       Pune
4650    Masters   27  New Delhi
4651  Bachelors   30  Bangalore

[2764 rows x 3 columns]

In [15]:
df['Experience_Age_Ratio'] = df['ExperienceInCurrentDomain'] / df['Age']

In [16]:
df.head()

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot,Experience_Age_Ratio
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0,0.000000
1,Bachelors,2013,Pune,1,28,Female,No,3,1,0.107143
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0,0.052632
3,Masters,2016,Bangalore,3,27,Male,No,5,1,0.185185
4,Masters,2017,Pune,3,24,Male,Yes,2,1,0.083333

In [17]:
df.to_csv('cleaned_data.csv', index=False)